### ISSUE TITLE
Search result

### ISSUE THREAD

**Issue by ghost** [jainishsenjaliya/js_paginate#1]
Hi
Thanks for your extension, It works fine, except for the serch results (with news for examples)
If I clicked on the page 2, the page is empty. I think the search parameters are lost ?
Thanks for your help

**Comment by jainishsenjaliya** [comment]
I don't think its issue..its working fine for me.

Have you include as static template in typoscript ??

Let me know in which typo version are you working on ??

**Comment by ghost** [comment]
Yes, the static is included.
I'm using TYPO3 7.6.5

**Comment by jainishsenjaliya** [comment]
I have tested with extra parameter and its working fine for me. 

i think you missed some configuration.

**Comment by ghost** [comment]
I have tested with a clean local TYPO3.
Only news and js_paginate.
Here is the fluid in the searchresult.html of ext:news

`<pg:Paginate objects="{news}" as="paginatedObject" configuration="{itemsPerPage: 1, insertAbove: 1, insertBelow: 1, maximumVisiblePages: 5}">
    <f:for each="{paginatedObject}" as="newsItem">
        <f:render partial="List/Item" arguments="{newsItem: newsItem, settings:settings, className:className, view:'list'}" />
    </f:for>
</pg:Paginate>`

What did I miss ?
Thanks for your help !

**Comment by jainishsenjaliya** [comment]
sorry for delay in reply..

can you please do print<f:debug> {paginatedObject} /f:debug

are you getting data ??

**Comment by ghost** [comment]
The debug (in the f:for) returns ' Array ' (7 chars)

**Comment by thombeck** [comment]
Finally, I got data in the debug if the namespace pg is before the news namespace.
But nothing on page 2

**Comment by thombeck** [comment]
If you want, I can give you a ftp access to make some tests on my server

**Comment by jainishsenjaliya** [comment]
you can reach me on skype :)

My skype id is : jainishsenjaliya

**Comment by jainishsenjaliya** [comment]
Is it working now ?

Sorry for delay in reply
