### ISSUE TITLE
Changing the Default Template

### ISSUE THREAD

**Issue by yu-ahmed** [jainishsenjaliya/js_paginate#2]
Is there a way to overwrite the template ?
I used the usual way via typoscript, but it didnt work.
Here my trys:

plugin.tx_jspaginate  {
  templateFile = myPath
 view {
  templateRootPaths.10 = myPath
  templateRootPath = myPath
  defaultTemplate = myPath
  widget {
   TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper {
    templateRootPath = myPath
   }
   Tx_JsPaginate_ViewHelpers_Widget_PaginateViewHelper {
      templateRootPath = myPath
    }
  }
 }
 widget.TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper.templateRootPath = myPath
}

**Comment by jainishsenjaliya** [comment]
You just need to install pagination extension. 

wherever you want to use you have to first declare name of in your template file

> **{namespace pg=JS\JsPaginate\ViewHelpers}**

then after we can use following pagination script. and need to add our records [ array ] in objects 

<pg:Paginate objects="{faq}" as="paginatedObject" configuration="{itemsPerPage: 5, insertAbove: 1, insertBelow: 1, maximumVisiblePages: 5, displayDots: 0}">
	<div class="faq-list">
		<f:for each="{paginatedObject}" as="list" iteration="itemIteration">
			<div class="even {f:if(condition: itemIteration.isOdd , then: 'odd')}">
				{paginatedObject.title}
			</div>
		</f:for>
	</div>
</pg:Paginate>

I have used in my FAQ extension. you may check out in following file

> https://github.com/jainishsenjaliya/js_faq/blob/master/Resources/Private/Partials/Template/Default.html

**Comment by yu-ahmed** [comment]
I implemented it already and it works, but i want to change something in js_paginate/Resources/Templates/Paginate/Index.html

thats why i want to shift that template from to a another extension.
